// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jesaannwsmhdvefdhzno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Implc2Fhbm53c21oZHZlZmRoem5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNjkzMzksImV4cCI6MjA2Mzc0NTMzOX0.2C7F9_OH3nkBNz1cwYd9N_jH9mgXwfAH-To87EUPEv8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});